// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

/*
 *	 Kit.h
 * 
 *  Kit class header file: This class represents a kit through it's kit name and 
 *  composing parts' numbers and quantities required.  Functions are provided to 
 *  construct a new kit object from a CSV file describing it, get and set the 
 *  kit's name, and to add parts to the kit.
 * 
 *  Author: Mike Ricci
 *  Date: 20140711
 */

#ifndef KIT_H
#define KIT_H

/************************************************************
 Kit class header
 ************************************************************/

#include <array>
#include <sstream>
#include <string>
#include <map>
#include <vector>
#include <fstream>
#include "Part.h"

class Kit 
{

public:

	Kit();
	Kit(std::string /*in*/filepath);
	virtual ~Kit();
	void addPart(std::string qty, std::string partNo, std::string desc);
	void appendDesc(std::string partNo, std::string desc);
	bool hasPart(std::string partNo) const;
	std::array<std::string, 3> parseLine(std::string line);
	std::string partQty(std::string partNo) const;
	std::string getDesc(std::string partNo) const;
	std::string getKitNo() const;
	void setKitNo(std::string /*in*/kitNo);

private:

	std::string kitNo;
	std::map<std::string, std::string> parts;
	static std::map<std::string, Part> partsCatalog;
	static std::vector<std::string> appended;

};

/************************************************************
 End of kit class header
 ************************************************************/

#endif
