// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

/*  KitList.cpp
 * 
 *  Source file for the KitList class: This class represents a group of kits and
 *  contains their kit and part objects.  Functions are provided to add kits and
 *  parts to the maps.
 */

/************************************************************
 kitList class body
 ************************************************************/

// include associated header file
#include "KitList.h"

//CONSTRUCTOR
KitList::KitList(std::string path)
{
//boost filesystem
}

//VIRTUAL DESTRUCTOR
KitList::~KitList()
{

}

//MEMBER FUNCTIONS

//The function addKit() creates a kit object in the kits map with the passed name.
void KitList::addKit(std::string kitNo)
{
	Kit tempKit = Kit();
	tempKit.setKitNo(kitNo);
	this->kits.insert(std::pair<std::string, Kit>(kitNo, tempKit));
}

//The function addPart() creates a part object in the parts map with the passed
//name and description.
void KitList::addPart(std::string partNo, std::string desc)
{
	//this->parts.insert(std::pair<std::string, Part>(partNo, Part(partNo, desc)));
}

//The function appendDesc() adds more to the description of a part in the parts map.
void KitList::appendDesc(std::string partNo, std::string desc)
{
	//std::string tempDesc = this->parts.at(partNo).getDesc();
	//this->parts.at(partNo).setDesc(tempDesc + desc);
}

//The function queryPart searches the kit objects contained in the kits map for
//instances of the passed part number.  It prints to the console the names of the
//kits which include the part and the quantity they require.
void KitList::queryPart(std::string partNo) const
{
	//make bingo map to store kits containing the part and the respective quantity reqd
	
	//iterate through all kits
		//iterate through all parts in the given kit
			//if the kit contains the part, add the kitNo and qty to bingo

	//print contents of bingo map
}

/************************************************************
 End of kitList class body
 ************************************************************/