// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

/*
 *	 Part.h
 * 
 *  Part class header file: This class represents a part through it's part
 *  number and description.  Functions are provided to get and set those two
 *  private attributes.
 * 
 *  Author: Mike Ricci
 *  Date: 20140711
 */

#ifndef PART_H
#define PART_H

/************************************************************
 Part class header
 ************************************************************/

#include <string>

class Part 
{

public:

	Part(std::string /*in*/partNo, std::string /*in*/desc);
	virtual ~Part();
	std::string getDesc() const;
	std::string getPartNo() const;
	void setDesc(std::string /*in*/desc);
	void setPartNo(std::string /*in*/partNo);

private:

	std::string partNo;
	std::string desc;

};

/************************************************************
 End of part class header
 ************************************************************/

#endif
